// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDePJdE_yQ9ml7oPYyGWFXDkV5ndq7jjBI',
    appId: '1:330824416065:web:01d4f3079dec9cef8a3fc0',
    messagingSenderId: '330824416065',
    projectId: 'crimeapp-40f21',
    authDomain: 'crimeapp-40f21.firebaseapp.com',
    storageBucket: 'crimeapp-40f21.firebasestorage.app',
    measurementId: 'G-90ZL8DNMVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVH4RUU6cFxAofGfmGI3EtUxGj9zbIJV4',
    appId: '1:330824416065:android:dbc8a27f93f8d5078a3fc0',
    messagingSenderId: '330824416065',
    projectId: 'crimeapp-40f21',
    storageBucket: 'crimeapp-40f21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaaUpk-zZLTDj9EHb_qVbZurGWFfZPu3c',
    appId: '1:330824416065:ios:0824194af027ae898a3fc0',
    messagingSenderId: '330824416065',
    projectId: 'crimeapp-40f21',
    storageBucket: 'crimeapp-40f21.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaaUpk-zZLTDj9EHb_qVbZurGWFfZPu3c',
    appId: '1:330824416065:ios:0824194af027ae898a3fc0',
    messagingSenderId: '330824416065',
    projectId: 'crimeapp-40f21',
    storageBucket: 'crimeapp-40f21.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDePJdE_yQ9ml7oPYyGWFXDkV5ndq7jjBI',
    appId: '1:330824416065:web:01d4f3079dec9cef8a3fc0',
    messagingSenderId: '330824416065',
    projectId: 'crimeapp-40f21',
    authDomain: 'crimeapp-40f21.firebaseapp.com',
    storageBucket: 'crimeapp-40f21.firebasestorage.app',
    measurementId: 'G-90ZL8DNMVX',
  );
}
